### ISSUE TITLE
Time series forecasting using LSTM

### ISSUE THREAD

**Issue by 26medias** [nlintz/TensorFlow-Tutorials#38]
Hi,

Thanks for those examples, they are very useful.

If you are still working on more examples, it'd be awesome to have an example of time series forecasting using LSTM. There's a lot of search for this, and no working example so far.

It's mostly the preparation of the input data that is confusing for me.

**Comment by hunkim** [comment]
I think it's a very good idea. Do you have some data for that?

**Comment by 26medias** [comment]
A simple sin?
It's an easy signal, easy to train with low error.

A Keras tutorial actually uses a sin for their example:
http://danielhnyk.cz/predicting-sequences-vectors-keras-using-rnn-lstm/

**Comment by hunkim** [comment]
Sounds good. I'll look into it. BTW, if you can come up with a PR, it would be also wonderful.

**Comment by 26medias** [comment]
PR?

**Comment by hunkim** [comment]
I meant a pull request. :-)

**Comment by 26medias** [comment]
Oh ok :)

I don't have anything to contribute at the moment.
I'm still in the transition from JS to Python, my code is not pretty.

I wish there was a good bridge to use TF in NodeJS :)

**Comment by nlintz** [comment]
Before I started machine learning I was a bigtime node hacker so I feel your pain. Karpathy wrote some pretty cool convnet stuff for javascript which I'd encourage you to check out if you have the time. 
http://cs.stanford.edu/people/karpathy/convnetjs/

**Comment by 26medias** [comment]
I already played with it quite a bit (https://github.com/26medias/Kobol)
But it's very slow to train. Being able to use GPUs is much more efficient to test models faster.
