### ISSUE TITLE
The IPython Notebook Format

### ISSUE THREAD

**Issue by hunkim** [nlintz/TensorFlow-Tutorials#55]
I think having ipynb would be useful to see the results quickly. 

@chahuja, could you help?

**Comment by chahuja** [comment]
Sure. We could divide the scripts into multiple blocks to make it more useful. And use the inline plotting functionality to see the results in the notebook itself.

**Comment by chahuja** [comment]
Would it be useful to have the notebook with outputs printed already?

**Comment by hunkim** [comment]
I think so.

**Comment by hunkim** [comment]
One potential issue is syncing py and ipynb files. Once people update py, should we also update all ipynb files manually? Is there any way to automatically sync?

**Comment by chahuja** [comment]
There is a way to convert ipynb files to python files but not vice-versa

    jupyter nbconvert <ipynb-file> --to=script > <python-file>

**Comment by hunkim** [comment]
Super! Once we have all ipynb files, we can encourage developers to send a
PR on ipynb files only. We need a simple script to generate py files.

**Comment by chahuja** [comment]
Created a pull request with an inital version

Could you run the `05_convolutional_net.ipynb` on your machine? For some reason convolution functions are not working on my build right now.

**Comment by hunkim** [comment]
I'll check that later. Should we add a script to convert from ipynb to py and ask other developers to edit only ipynb?

**Comment by chahuja** [comment]
Yeah, that would be a good idea. But, what would be better, a script to convert all ipynb files to their respective py files or one file at a time?

**Comment by hunkim** [comment]
One script makes sense to me.

**Comment by chahuja** [comment]
For use by contributors at a later stage, conversion of one file at a time makes more sense.
