### ISSUE TITLE
Does not support python 3.3

### ISSUE THREAD

**Issue by Foorack** [nlintz/TensorFlow-Tutorials#7]
Tensorflow recently released official support for python 3.3.
I just wanted to mention that this tutorial is not working in the latest version of python. :)

**Comment by hunkim** [comment]
What are the error messages?

**Comment by Foorack** [comment]
An example is the print statements. https://docs.python.org/3/whatsnew/3.0.html

Example:https://github.com/nlintz/TensorFlow-Tutorials/blob/master/2_logistic_regression.py#L35
